server:
  port: 7001
  servlet:
    context-path: /homepage-course

spring:
  application:
    name: eureka-client-homepage-course
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis_plus_db?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    username: root
    password: lhw123456
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

  redis:
    host: 192.168.236.128
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    timeout: 5000

##必须先启动  注册服务，否则网络会拒绝连接
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
